import os
os.system("cd /home/mtowner/minetest && cmake . -DRUN_IN_PLACE=TRUE -DBUILD_SERVER=TRUE -DBUILD_CLIENT=FALSE -DIRRLICHT")
os.system("cd /home/mtowner/minetest/mods && rm -fr mesecons")
os.system("cd /home/mtowner/minetest/mods && git clone https://github.com/minetest-mods/mesecons.git")
os.system("cd /home/mtowner/minetest/mods && git clone https://github.com/minetest-mods/areas.git")
os.system("cd /home/mtowner/minetest/mods && git clone https://github.com/minetest-mods/unified_inventory.git")
os.system("cd /home/mtowner/minetest/mods && git clone https://github.com/minetest-mods/moreblock")
os.system("cd /home/mtowner/minetest/mods && https://github.com/minetest-mods/moreores.git")
os.system("cd /home/mtowner/minetest/mods && git clone https://github.com/minetest-mods/skinsdb.git")
os.system("cd /home/mtowner/minetest/mods && git clone https://github.com/minetest-mods/maptools.git")
os.system("cd /home/mtowner/minetest/mods && git clone https://github.com/minetest-mods/xban2.git")
os.system("cd /home/mtowner/minetest/mods && git clone https://github.com/EngineHub/WorldEdit.git")
os.system("cd /home/mtowner/minetest/mods && git clone https://github.com/D00Med/vehicles.git")
os.system("cd /home/mtowner/minetest/mods && git clone https://github.com/octacian/ranks.git")
os.system("cd /home/mtowner/minetest/mods && git clone https://github.com/minetest-mods/i3.git")
os.system("cd /home/mtowner/minetest/mods && git clone https://github.com/minetest-mods/3d_armor.git")
os.system("cd /home/mtowner/minetest/mods && git clone https://github.com/orwell96/advtrains.git")
os.system("cd /home/mtowner/minetest/mods && git clone https://github.com/minetest-mirrors/farming.git")
os.system("cd /home/mtowner/minetest/mods && git clone https://github.com/Dragonop/tools_obsidian.git")
os.system("cd /home/mtowner/minetest/mods && git clone https://github.com/Athemis/mobs_redo.git")
